import Link from "next/link";

import { SITE_NAME } from "@/lib/site";
import { cn } from "@/lib/utils";

/** The supplied mark is shared by the header, footer and intro.
 * Keep data-logo-mark on the measured box used by the intro transition.
 */
export function LogoMark({ className }: { className?: string }) {
  return (
    <span
      aria-hidden="true"
      data-logo-mark
      data-bleed=""
      className={cn(
        "brand-logo-mark size-8 shrink-0",
        className,
      )}
    >
      {/*
        Two files, not one file and a filter.

        The mark is two-tone: ink structure with sand pans. On the ink footer,
        the docked capsule and in dark mode it used to be pushed through
        `brightness(0) invert(0.93)`, which flattens it to one near-white
        silhouette and throws the sand away — a visible change to the logo. No
        CSS filter can lighten the ink and leave the sand alone: invert turns
        sand into a dark blue, grayscale turns it dark.

        So the light-surface variant is a real asset with the ink repainted to
        bone and the sand untouched, generated by scripts/make-logo-variant.ts.
        CSS shows whichever one belongs on the surface underneath. Both are in
        the markup so the swap costs no JavaScript and cannot flash.
      */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src="/logos/indaca_logo7.png"
        alt=""
        width={500}
        height={500}
        decoding="async"
        data-on="light"
      />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src="/logos/indaba-mark-light.png"
        alt=""
        width={500}
        height={500}
        decoding="async"
        data-on="dark"
      />
    </span>
  );
}

export function BrandLogo({
  className,
  withMark = true,
  href = "/",
  markClassName,
}: {
  className?: string;
  withMark?: boolean;
  href?: string | null;
  markClassName?: string;
}) {
  const content = (
    <>
      {withMark && <LogoMark className={markClassName} />}
      <span className="brand-wordmark font-heading text-xl font-medium tracking-[-0.02em]">
        {SITE_NAME}
      </span>
    </>
  );

  /*
    No focus ring classes. The global :focus-visible rule in globals.css §3
    already draws a 2px bronze outline at 2px offset on everything, and adding
    a second ring here would paint two rings around the same element in light
    mode and disagree with it in dark.

    There is also no sr-only copy of the name any more. The wordmark used to be
    split into two coloured spans, which is why one existed; now it is a single
    text node that reads correctly on its own, and a second copy inside the
    link would announce "Indaba Indaba".
  */
  const classes = cn(
    "inline-flex items-center gap-2 rounded-full",
    className,
  );

  if (href === null) {
    return <span className={classes}>{content}</span>;
  }

  return (
    <Link href={href} className={classes} aria-label={`${SITE_NAME} home`}>
      {content}
    </Link>
  );
}
