// Generated by scripts/fetch-logos.ts. Do not edit by hand.
// Run `npm run logos` to refresh.

export type LogoFile = {
  file: string;
  shape: "mark" | "wordmark";
  width: number | null;
  height: number | null;
};

export const LOGO_FILES: Record<string, LogoFile> = {
  "asana": { file: "/logos/asana.svg", shape: "mark", width: 24, height: 24 },
  "bamboohr": { file: "/logos/bamboohr.png", shape: "wordmark", width: 1479, height: 227 },
  "bitrix24": { file: "/logos/bitrix24.svg", shape: "wordmark", width: 174, height: 33 },
  "clickup": { file: "/logos/clickup.svg", shape: "mark", width: 24, height: 24 },
  "freshbooks": { file: "/logos/freshbooks.png", shape: "mark", width: 96, height: 96 },
  "freshworks": { file: "/logos/freshworks.png", shape: "mark", width: 180, height: 180 },
  "hubspot": { file: "/logos/hubspot.svg", shape: "mark", width: 24, height: 24 },
  "insightly": { file: "/logos/insightly.png", shape: "mark", width: 192, height: 192 },
  "labournet": { file: "/logos/labournet.png", shape: "mark", width: 192, height: 192 },
  "microsoftdynamics": { file: "/logos/microsoftdynamics.png", shape: "mark", width: 128, height: 128 },
  "monday": { file: "/logos/monday.png", shape: "mark", width: 256, height: 256 },
  "odoo": { file: "/logos/odoo.svg", shape: "mark", width: 24, height: 24 },
  "omniaccounts": { file: "/logos/omniaccounts.png", shape: "mark", width: 192, height: 192 },
  "paysoft": { file: "/logos/paysoft.svg", shape: "wordmark", width: 634.7, height: 259.3 },
  "payspace": { file: "/logos/payspace.svg", shape: "wordmark", width: 3211, height: 600 },
  "peoplehr": { file: "/logos/peoplehr.png", shape: "mark", width: 196, height: 196 },
  "pipedrive": { file: "/logos/pipedrive.png", shape: "mark", width: 144, height: 144 },
  "quickbooks": { file: "/logos/quickbooks.svg", shape: "mark", width: 24, height: 24 },
  "quickeasy": { file: "/logos/quickeasy.png", shape: "mark", width: 50, height: 61 },
  "sage": { file: "/logos/sage.svg", shape: "mark", width: 24, height: 24 },
  "salesforce": { file: "/logos/salesforce.svg", shape: "mark", width: 92, height: 64 },
  "sap": { file: "/logos/sap.svg", shape: "mark", width: 24, height: 24 },
  "simplepay": { file: "/logos/simplepay.png", shape: "mark", width: 80, height: 80 },
  "syspro": { file: "/logos/syspro.svg", shape: "wordmark", width: 450.55, height: 119.82 },
  "trello": { file: "/logos/trello.svg", shape: "mark", width: 24, height: 24 },
  "wave": { file: "/logos/wave.svg", shape: "wordmark", width: 1625.39, height: 467.88 },
  "workday": { file: "/logos/workday.png", shape: "mark", width: 32, height: 32 },
  "wrike": { file: "/logos/wrike.png", shape: "mark", width: 48, height: 48 },
  "xero": { file: "/logos/xero.svg", shape: "mark", width: 24, height: 24 },
  "zoho": { file: "/logos/zoho.svg", shape: "mark", width: 24, height: 24 },
};
