// Generated by scripts/fetch-logos.ts. Do not edit by hand.
// Run `npm run logos` to refresh.

export type LogoFile = {
  file: string;
  shape: "mark" | "wordmark";
  width: number | null;
  height: number | null;
};

export const LOGO_FILES: Record<string, LogoFile> = {
  "asana": { file: "/logos/asana.svg", shape: "mark", width: 24, height: 24 },
  "bamboohr": { file: "/logos/bamboohr.png", shape: "wordmark", width: 1479, height: 227 },
  "bitrix24": { file: "/logos/bitrix24.svg", shape: "wordmark", width: 174, height: 33 },
  "clickup": { file: "/logos/clickup.svg", shape: "mark", width: 24, height: 24 },
  "hubspot": { file: "/logos/hubspot.svg", shape: "mark", width: 24, height: 24 },
  "monday": { file: "/logos/monday.png", shape: "mark", width: 256, height: 256 },
  "odoo": { file: "/logos/odoo.svg", shape: "mark", width: 24, height: 24 },
  "payspace": { file: "/logos/payspace.svg", shape: "wordmark", width: 3211, height: 600 },
  "quickbooks": { file: "/logos/quickbooks.svg", shape: "mark", width: 24, height: 24 },
  "sage": { file: "/logos/sage.svg", shape: "mark", width: 24, height: 24 },
  "salesforce": { file: "/logos/salesforce.svg", shape: "mark", width: 92, height: 64 },
  "sap": { file: "/logos/sap.svg", shape: "mark", width: 24, height: 24 },
  "simplepay": { file: "/logos/simplepay.png", shape: "mark", width: 80, height: 80 },
  "syspro": { file: "/logos/syspro.svg", shape: "wordmark", width: 450.55, height: 119.82 },
  "trello": { file: "/logos/trello.svg", shape: "mark", width: 24, height: 24 },
  "wave": { file: "/logos/wave.svg", shape: "wordmark", width: 1625.39, height: 467.88 },
  "xero": { file: "/logos/xero.svg", shape: "mark", width: 24, height: 24 },
  "zoho": { file: "/logos/zoho.svg", shape: "mark", width: 24, height: 24 },
};
