// Generated by scripts/measure-logos.ts. Do not edit by hand.
// Run `npx tsx scripts/measure-logos.ts` to refresh.
//
// height is the rendered height in px that gives this mark the same ink area
// as every other mark in the row. aspect is width / height of the source file,
// which is what reserves the correct width so the marquee cannot shift.
//
// The row is painted as flat silhouettes, so ink area IS optical weight. See
// the header of the script for why a bounding box is the wrong unit here.

export type LogoOptics = { height: number; aspect: number };

export const LOGO_OPTICS: Record<string, LogoOptics> = {
  "asana": { height: 32, aspect: 1.000 },
  "bamboohr": { height: 22, aspect: 6.515 },
  "bitrix24": { height: 22, aspect: 5.273 },
  "clickup": { height: 37, aspect: 1.000 },
  "freshbooks": { height: 22, aspect: 1.000 },
  "freshworks": { height: 24, aspect: 1.000 },
  "hubspot": { height: 38, aspect: 1.000 },
  "insightly": { height: 26, aspect: 1.000 },
  "labournet": { height: 38, aspect: 1.000 },
  "microsoftdynamics": { height: 22, aspect: 1.000 },
  "monday": { height: 38, aspect: 1.000 },
  "odoo": { height: 38, aspect: 1.000 },
  "omniaccounts": { height: 32, aspect: 1.000 },
  "paysoft": { height: 38, aspect: 2.439 },
  "payspace": { height: 22, aspect: 5.352 },
  "peoplehr": { height: 38, aspect: 1.000 },
  "pipedrive": { height: 24, aspect: 1.000 },
  "quickbooks": { height: 27, aspect: 1.000 },
  "quickeasy": { height: 38, aspect: 0.820 },
  "sage": { height: 38, aspect: 1.000 },
  "salesforce": { height: 22, aspect: 1.440 },
  "sap": { height: 38, aspect: 1.000 },
  "simplepay": { height: 38, aspect: 1.000 },
  "syspro": { height: 22, aspect: 3.750 },
  "trello": { height: 24, aspect: 1.000 },
  "wave": { height: 22, aspect: 3.488 },
  "workday": { height: 37, aspect: 1.000 },
  "wrike": { height: 38, aspect: 1.000 },
  "xero": { height: 25, aspect: 1.000 },
  "zoho": { height: 38, aspect: 1.000 },
};

/** The height to render a mark at. Unmeasured marks fall back to the median. */
export function opticalHeight(key: string | null | undefined): number {
  return (key && LOGO_OPTICS[key]?.height) || 32;
}
