/**
 * Generates data/pricing/SOURCES.md from lib/content/pricing.ts.
 *
 *   npx tsx scripts/pricing-sources.ts
 *
 * Generated rather than hand written so the audit trail can never drift from
 * the figures the site actually uses.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { FX, PRICING, resolvePrice, type Verification } from "../lib/content/pricing";

const LABEL: Record<Verification, string> = {
  "vendor-page": "Verified on vendor page",
  "vendor-page-indexed": "From vendor page via search index, needs manual check",
  "quote-only": "Vendor publishes no list price",
  unconfirmed: "Not established, needs manual check",
};

const ORDER: Verification[] = [
  "vendor-page",
  "vendor-page-indexed",
  "unconfirmed",
  "quote-only",
];

function money(amount: number | null, currency: string) {
  if (amount === null) return "none published";
  const symbol = { ZAR: "R", USD: "US$", GBP: "£", EUR: "€" }[currency] ?? `${currency} `;
  return `${symbol}${amount}`;
}

async function main() {
  const records = Object.values(PRICING);
  const counts = ORDER.map((level) => ({
    level,
    n: records.filter((r) => r.verification === level).length,
  }));

  const lines: string[] = [
    "# Pricing sources",
    "",
    "Audit trail for every price on the site. Generated by",
    "`npx tsx scripts/pricing-sources.ts` from `lib/content/pricing.ts`.",
    "Do not edit by hand.",
    "",
    "## Conversion basis",
    "",
    `Several vendors do not quote in rand. Those figures are converted, never invented, at:`,
    "",
    `- **Source:** ${FX.source}`,
    `- **Date:** ${FX.date}`,
    `- **USD to ZAR:** ${FX.usdToZar}`,
    `- **GBP to ZAR:** ${FX.gbpToZar}`,
    `- **EUR to ZAR:** ${FX.eurToZar}`,
    "",
    "A converted figure is not the same promise as a price the vendor actually",
    "charges in rand, and the profile page says so on each affected product.",
    "",
    "## Coverage",
    "",
    "| Verification level | Products |",
    "|---|---|",
    ...counts.map((c) => `| ${LABEL[c.level]} | ${c.n} |`),
    `| **Total** | **${records.length}** |`,
    "",
    "## Products needing a manual check in a browser",
    "",
    "These could not be read automatically. Sage in particular returns 403 to",
    "every automated request, which is why six Sage products sit here.",
    "",
  ];

  const needsCheck = records.filter(
    (r) => r.verification === "unconfirmed" || r.verification === "vendor-page-indexed",
  );

  for (const record of needsCheck) {
    lines.push(`- **${record.slug}** — ${record.sourceUrl}`);
  }

  lines.push("", "## Every record", "");

  for (const level of ORDER) {
    const group = records.filter((r) => r.verification === level);
    if (group.length === 0) continue;

    lines.push(`### ${LABEL[level]}`, "");
    for (const record of group) {
      const resolved = resolvePrice(record.slug);
      lines.push(
        `#### ${record.slug}`,
        "",
        `- Published price: ${money(record.startingAmount, record.currency)} per ${record.period}`,
        `- In rand: ${resolved?.zar === null ? "none published" : `R${resolved?.zar}`}${resolved?.converted ? " (converted)" : ""}`,
        `- VAT: ${record.vatInclusive === true ? "included" : record.vatInclusive === false ? "excluded" : "not stated"}`,
        `- Free trial: ${record.freeTrialDays ? `${record.freeTrialDays} days` : "none"}`,
        `- Free plan: ${record.freeVersion ? "yes" : "no"}`,
        `- Source: ${record.sourceUrl}`,
        `- Checked: ${record.checkedAt}`,
        `- Notes: ${record.notes}`,
        "",
      );
    }
  }

  const outDir = path.join(process.cwd(), "data", "pricing");
  await mkdir(outDir, { recursive: true });
  await writeFile(path.join(outDir, "SOURCES.md"), lines.join("\n"), "utf8");

  console.log(`SOURCES.md written for ${records.length} products`);
  for (const c of counts) console.log(`  ${LABEL[c.level].padEnd(52)} ${c.n}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
